[tool.black]
line-length = 120
target-version = ['py37']
include = '\.pyi?$'
skip-string-normalization = 1

[tool.coverage.run]
source = ['snail','cli']

[tool.coverage.report]
show_missing = true
skip_covered = true

[tool.pytest.ini_options]
minversion = "6.0"
addopts = "--disable-socket"
testpaths = ["tests", "snail", "cli"]
