# generated automatically from https://www.snailtrail.art/main.44a30b30721e5995.js - DO NOT MODIFY

CONTRACT = '0x2565FF39808385749e94365F8FAf3C441e74DeD2'

ABI = [
    {
        'inputs': [{'internalType': 'address', 'name': 'nftAddress', 'type': 'address'}],
        'stateMutability': 'nonpayable',
        'type': 'constructor',
    },
    {
        'anonymous': False,
        'inputs': [
            {
                'components': [
                    {'internalType': 'uint256', 'name': 'itemId', 'type': 'uint256'},
                    {'internalType': 'uint256', 'name': 'tokenId', 'type': 'uint256'},
                    {'internalType': 'address', 'name': 'seller', 'type': 'address'},
                    {'internalType': 'uint256', 'name': 'price', 'type': 'uint256'},
                    {'internalType': 'uint256', 'name': 'timeout', 'type': 'uint256'},
                    {'internalType': 'bool', 'name': 'isListed', 'type': 'bool'},
                ],
                'indexed': False,
                'internalType': 'struct SnailTrailGeneMarketplace.MarketGeneItem',
                'name': 'newItem',
                'type': 'tuple',
            },
            {'indexed': False, 'internalType': 'uint256', 'name': 'remainder', 'type': 'uint256'},
        ],
        'name': 'ListGene',
        'type': 'event',
    },
    {
        'anonymous': False,
        'inputs': [
            {'indexed': True, 'internalType': 'address', 'name': 'previousOwner', 'type': 'address'},
            {'indexed': True, 'internalType': 'address', 'name': 'newOwner', 'type': 'address'},
        ],
        'name': 'OwnershipTransferred',
        'type': 'event',
    },
    {
        'anonymous': False,
        'inputs': [
            {
                'components': [
                    {
                        'components': [
                            {'internalType': 'uint256', 'name': 'itemId', 'type': 'uint256'},
                            {'internalType': 'uint256', 'name': 'tokenId', 'type': 'uint256'},
                            {'internalType': 'address', 'name': 'seller', 'type': 'address'},
                            {'internalType': 'uint256', 'name': 'price', 'type': 'uint256'},
                            {'internalType': 'uint256', 'name': 'timeout', 'type': 'uint256'},
                            {'internalType': 'bool', 'name': 'isListed', 'type': 'bool'},
                        ],
                        'internalType': 'struct SnailTrailGeneMarketplace.MarketGeneItem',
                        'name': 'item',
                        'type': 'tuple',
                    },
                    {'internalType': 'address', 'name': 'buyer', 'type': 'address'},
                ],
                'indexed': False,
                'internalType': 'struct SnailTrailGeneMarketplace.Purchase',
                'name': 'item',
                'type': 'tuple',
            }
        ],
        'name': 'PurchaseGene',
        'type': 'event',
    },
    {
        'anonymous': False,
        'inputs': [
            {'indexed': False, 'internalType': 'uint256', 'name': 'tokenId', 'type': 'uint256'},
            {'indexed': False, 'internalType': 'enum SnailGender', 'name': 'gender', 'type': 'uint8'},
        ],
        'name': 'SnailGenderChanged',
        'type': 'event',
    },
    {
        'anonymous': False,
        'inputs': [
            {
                'components': [
                    {'internalType': 'uint256', 'name': 'itemId', 'type': 'uint256'},
                    {'internalType': 'uint256', 'name': 'tokenId', 'type': 'uint256'},
                    {'internalType': 'address', 'name': 'seller', 'type': 'address'},
                    {'internalType': 'uint256', 'name': 'price', 'type': 'uint256'},
                    {'internalType': 'uint256', 'name': 'timeout', 'type': 'uint256'},
                    {'internalType': 'bool', 'name': 'isListed', 'type': 'bool'},
                ],
                'indexed': False,
                'internalType': 'struct SnailTrailGeneMarketplace.MarketGeneItem',
                'name': 'marketItem',
                'type': 'tuple',
            },
            {'indexed': False, 'internalType': 'uint256', 'name': 'remainder', 'type': 'uint256'},
        ],
        'name': 'UpdateGeneItem',
        'type': 'event',
    },
    {
        'anonymous': False,
        'inputs': [
            {'indexed': False, 'internalType': 'uint256', 'name': 'tokenId', 'type': 'uint256'},
            {'indexed': False, 'internalType': 'uint256', 'name': 'remainder', 'type': 'uint256'},
        ],
        'name': 'WithdrawGene',
        'type': 'event',
    },
    {
        'inputs': [{'internalType': 'address', 'name': 'newContract', 'type': 'address'}],
        'name': 'addRecognizeContract',
        'outputs': [],
        'stateMutability': 'nonpayable',
        'type': 'function',
    },
    {'inputs': [], 'name': 'enableMarketplace', 'outputs': [], 'stateMutability': 'nonpayable', 'type': 'function'},
    {
        'inputs': [
            {'internalType': 'address', 'name': 'femaleOwner', 'type': 'address'},
            {'internalType': 'uint256', 'name': 'femaleItemId', 'type': 'uint256'},
            {'internalType': 'uint256', 'name': 'maleItemId', 'type': 'uint256'},
        ],
        'name': 'fullfillGeneSale',
        'outputs': [],
        'stateMutability': 'nonpayable',
        'type': 'function',
    },
    {
        'inputs': [
            {'internalType': 'uint256', 'name': 'femaleItemId', 'type': 'uint256'},
            {'internalType': 'uint256', 'name': 'maleItemId', 'type': 'uint256'},
        ],
        'name': 'fullfillInHouseBreeding',
        'outputs': [],
        'stateMutability': 'nonpayable',
        'type': 'function',
    },
    {
        'inputs': [{'internalType': 'uint256', 'name': 'itemId', 'type': 'uint256'}],
        'name': 'getOwner',
        'outputs': [{'internalType': 'address', 'name': '', 'type': 'address'}],
        'stateMutability': 'view',
        'type': 'function',
    },
    {
        'inputs': [{'internalType': 'uint256', 'name': 'itemId', 'type': 'uint256'}],
        'name': 'getPrice',
        'outputs': [{'internalType': 'uint256', 'name': '', 'type': 'uint256'}],
        'stateMutability': 'view',
        'type': 'function',
    },
    {
        'inputs': [{'internalType': 'uint256', 'name': 'tokenId', 'type': 'uint256'}],
        'name': 'getSnailGender',
        'outputs': [{'internalType': 'enum SnailGender', 'name': '', 'type': 'uint8'}],
        'stateMutability': 'view',
        'type': 'function',
    },
    {
        'inputs': [{'internalType': 'uint256', 'name': 'itemId', 'type': 'uint256'}],
        'name': 'isActive',
        'outputs': [{'internalType': 'bool', 'name': '', 'type': 'bool'}],
        'stateMutability': 'view',
        'type': 'function',
    },
    {
        'inputs': [],
        'name': 'isBazaarOpen',
        'outputs': [{'internalType': 'bool', 'name': '', 'type': 'bool'}],
        'stateMutability': 'view',
        'type': 'function',
    },
    {
        'inputs': [{'internalType': 'address', 'name': 'newContract', 'type': 'address'}],
        'name': 'isContractRecognized',
        'outputs': [{'internalType': 'bool', 'name': 'isRecognized', 'type': 'bool'}],
        'stateMutability': 'view',
        'type': 'function',
    },
    {
        'inputs': [{'internalType': 'uint256', 'name': 'tokenID', 'type': 'uint256'}],
        'name': 'isGenderChangeAvailable',
        'outputs': [{'internalType': 'bool', 'name': '', 'type': 'bool'}],
        'stateMutability': 'view',
        'type': 'function',
    },
    {
        'inputs': [],
        'name': 'isGenderChangeEnabled',
        'outputs': [{'internalType': 'bool', 'name': '', 'type': 'bool'}],
        'stateMutability': 'view',
        'type': 'function',
    },
    {
        'inputs': [
            {'internalType': 'uint256', 'name': 'femaleTokenId', 'type': 'uint256'},
            {'internalType': 'uint256', 'name': 'maleTokenId', 'type': 'uint256'},
        ],
        'name': 'isIncubationPossible',
        'outputs': [{'internalType': 'bool', 'name': '', 'type': 'bool'}],
        'stateMutability': 'view',
        'type': 'function',
    },
    {
        'inputs': [
            {'internalType': 'uint256', 'name': 'tokenId', 'type': 'uint256'},
            {'internalType': 'uint256', 'name': 'price', 'type': 'uint256'},
        ],
        'name': 'listGene',
        'outputs': [],
        'stateMutability': 'nonpayable',
        'type': 'function',
    },
    {
        'inputs': [],
        'name': 'maxFemaleProductionCount',
        'outputs': [{'internalType': 'uint8', 'name': '', 'type': 'uint8'}],
        'stateMutability': 'view',
        'type': 'function',
    },
    {
        'inputs': [],
        'name': 'maxMaleProductionCount',
        'outputs': [{'internalType': 'uint8', 'name': '', 'type': 'uint8'}],
        'stateMutability': 'view',
        'type': 'function',
    },
    {
        'inputs': [],
        'name': 'owner',
        'outputs': [{'internalType': 'address', 'name': '', 'type': 'address'}],
        'stateMutability': 'view',
        'type': 'function',
    },
    {'inputs': [], 'name': 'pauseMarketplace', 'outputs': [], 'stateMutability': 'nonpayable', 'type': 'function'},
    {
        'inputs': [{'internalType': 'address', 'name': '', 'type': 'address'}],
        'name': 'recognizedContracts',
        'outputs': [{'internalType': 'bool', 'name': '', 'type': 'bool'}],
        'stateMutability': 'view',
        'type': 'function',
    },
    {
        'inputs': [{'internalType': 'address', 'name': 'contractAddress', 'type': 'address'}],
        'name': 'removeRecognizedContract',
        'outputs': [],
        'stateMutability': 'nonpayable',
        'type': 'function',
    },
    {'inputs': [], 'name': 'renounceOwnership', 'outputs': [], 'stateMutability': 'nonpayable', 'type': 'function'},
    {
        'inputs': [
            {'internalType': 'uint256', 'name': 'tokenId', 'type': 'uint256'},
            {'internalType': 'enum SnailGender', 'name': 'gender', 'type': 'uint8'},
        ],
        'name': 'setGender',
        'outputs': [],
        'stateMutability': 'nonpayable',
        'type': 'function',
    },
    {
        'inputs': [{'internalType': 'uint256', 'name': '', 'type': 'uint256'}],
        'name': 'snailGenderCounter',
        'outputs': [{'internalType': 'uint256', 'name': '', 'type': 'uint256'}],
        'stateMutability': 'view',
        'type': 'function',
    },
    {
        'inputs': [{'internalType': 'uint256', 'name': '', 'type': 'uint256'}],
        'name': 'snailGenderTracker',
        'outputs': [{'internalType': 'enum SnailGender', 'name': '', 'type': 'uint8'}],
        'stateMutability': 'view',
        'type': 'function',
    },
    {
        'inputs': [{'internalType': 'uint256', 'name': '', 'type': 'uint256'}],
        'name': 'snailIncubationTimeTracker',
        'outputs': [{'internalType': 'uint256', 'name': '', 'type': 'uint256'}],
        'stateMutability': 'view',
        'type': 'function',
    },
    {
        'inputs': [
            {'internalType': 'uint256', 'name': '', 'type': 'uint256'},
            {'internalType': 'uint256', 'name': '', 'type': 'uint256'},
        ],
        'name': 'snailIncubationTracker',
        'outputs': [{'internalType': 'uint8', 'name': '', 'type': 'uint8'}],
        'stateMutability': 'view',
        'type': 'function',
    },
    {
        'inputs': [{'internalType': 'uint256', 'name': 'tokenID', 'type': 'uint256'}],
        'name': 'timeToNextGenderChange',
        'outputs': [{'internalType': 'uint256', 'name': '', 'type': 'uint256'}],
        'stateMutability': 'view',
        'type': 'function',
    },
    {
        'inputs': [{'internalType': 'address', 'name': 'newOwner', 'type': 'address'}],
        'name': 'transferOwnership',
        'outputs': [],
        'stateMutability': 'nonpayable',
        'type': 'function',
    },
    {
        'inputs': [
            {'internalType': 'uint256', 'name': 'itemId', 'type': 'uint256'},
            {'internalType': 'uint256', 'name': 'price', 'type': 'uint256'},
        ],
        'name': 'updatePrice',
        'outputs': [],
        'stateMutability': 'nonpayable',
        'type': 'function',
    },
    {'inputs': [], 'name': 'withdrawBalance', 'outputs': [], 'stateMutability': 'nonpayable', 'type': 'function'},
    {
        'inputs': [{'internalType': 'contract IERC20', 'name': 'token', 'type': 'address'}],
        'name': 'withdrawErc20',
        'outputs': [],
        'stateMutability': 'nonpayable',
        'type': 'function',
    },
    {
        'inputs': [{'internalType': 'uint256', 'name': 'itemId', 'type': 'uint256'}],
        'name': 'withdrawMarketItem',
        'outputs': [],
        'stateMutability': 'nonpayable',
        'type': 'function',
    },
]
