# generated automatically from https://www.snailtrail.art/main.d3905bf907602c39.js - DO NOT MODIFY

CONTRACT = '0x58B699642f2a4b91Dd10800Ef852427B719dB1f0'

ABI = [
    {
        'anonymous': False,
        'inputs': [{'indexed': False, 'internalType': 'uint8', 'name': 'version', 'type': 'uint8'}],
        'name': 'Initialized',
        'type': 'event',
    },
    {
        'anonymous': False,
        'inputs': [
            {'indexed': False, 'internalType': 'uint256', 'name': 'raceID', 'type': 'uint256'},
            {'indexed': False, 'internalType': 'uint256', 'name': 'tokenID', 'type': 'uint256'},
            {'indexed': False, 'internalType': 'address', 'name': 'racerAddress', 'type': 'address'},
        ],
        'name': 'JoinedCompetitiveRace',
        'type': 'event',
    },
    {
        'anonymous': False,
        'inputs': [
            {'indexed': False, 'internalType': 'uint256', 'name': 'raceID', 'type': 'uint256'},
            {'indexed': False, 'internalType': 'uint256', 'name': 'tokenID', 'type': 'uint256'},
            {'indexed': False, 'internalType': 'address', 'name': 'racerAddress', 'type': 'address'},
        ],
        'name': 'JoinedDailyRace',
        'type': 'event',
    },
    {
        'anonymous': False,
        'inputs': [
            {'indexed': True, 'internalType': 'address', 'name': 'previousOwner', 'type': 'address'},
            {'indexed': True, 'internalType': 'address', 'name': 'newOwner', 'type': 'address'},
        ],
        'name': 'OwnershipTransferred',
        'type': 'event',
    },
    {
        'anonymous': False,
        'inputs': [{'indexed': False, 'internalType': 'uint256', 'name': 'raceID', 'type': 'uint256'}],
        'name': 'RewardDistributed',
        'type': 'event',
    },
    {
        'anonymous': False,
        'inputs': [
            {'indexed': False, 'internalType': 'address', 'name': 'beneficary', 'type': 'address'},
            {'indexed': False, 'internalType': 'uint256', 'name': 'amount', 'type': 'uint256'},
        ],
        'name': 'RewardsIssued',
        'type': 'event',
    },
    {'stateMutability': 'payable', 'type': 'fallback'},
    {
        'inputs': [],
        'name': 'autoClaimAfterResultEnabled',
        'outputs': [{'internalType': 'bool', 'name': '', 'type': 'bool'}],
        'stateMutability': 'view',
        'type': 'function',
    },
    {'inputs': [], 'name': 'claimRewards', 'outputs': [], 'stateMutability': 'nonpayable', 'type': 'function'},
    {
        'inputs': [],
        'name': 'claimableCompRewards',
        'outputs': [{'internalType': 'uint256', 'name': '', 'type': 'uint256'}],
        'stateMutability': 'view',
        'type': 'function',
    },
    {
        'inputs': [],
        'name': 'claimableDailyRewards',
        'outputs': [{'internalType': 'uint256', 'name': '', 'type': 'uint256'}],
        'stateMutability': 'view',
        'type': 'function',
    },
    {
        'inputs': [],
        'name': 'claimableRewards',
        'outputs': [{'internalType': 'uint256', 'name': '', 'type': 'uint256'}],
        'stateMutability': 'view',
        'type': 'function',
    },
    {
        'inputs': [{'internalType': 'address', 'name': '', 'type': 'address'}],
        'name': 'compRewardTracker',
        'outputs': [{'internalType': 'uint256', 'name': '', 'type': 'uint256'}],
        'stateMutability': 'view',
        'type': 'function',
    },
    {
        'inputs': [],
        'name': 'compTreasuryContract',
        'outputs': [{'internalType': 'address', 'name': '', 'type': 'address'}],
        'stateMutability': 'view',
        'type': 'function',
    },
    {
        'inputs': [{'internalType': 'uint256', 'name': '', 'type': 'uint256'}],
        'name': 'competitiveDistr',
        'outputs': [{'internalType': 'uint256', 'name': '', 'type': 'uint256'}],
        'stateMutability': 'view',
        'type': 'function',
    },
    {
        'inputs': [],
        'name': 'competitiveTotalDistr',
        'outputs': [{'internalType': 'uint256', 'name': '', 'type': 'uint256'}],
        'stateMutability': 'view',
        'type': 'function',
    },
    {
        'inputs': [{'internalType': 'uint256', 'name': '', 'type': 'uint256'}],
        'name': 'competitveRaceMaxRacerTracker',
        'outputs': [{'internalType': 'uint256', 'name': '', 'type': 'uint256'}],
        'stateMutability': 'view',
        'type': 'function',
    },
    {
        'inputs': [
            {'internalType': 'uint256', 'name': '', 'type': 'uint256'},
            {'internalType': 'address', 'name': '', 'type': 'address'},
        ],
        'name': 'competitveRaceUniqueEntryTracker',
        'outputs': [{'internalType': 'bool', 'name': '', 'type': 'bool'}],
        'stateMutability': 'view',
        'type': 'function',
    },
    {
        'inputs': [{'internalType': 'address', 'name': '', 'type': 'address'}],
        'name': 'dailyRewardTracker',
        'outputs': [{'internalType': 'uint256', 'name': '', 'type': 'uint256'}],
        'stateMutability': 'view',
        'type': 'function',
    },
    {
        'inputs': [],
        'name': 'dailyTreasuryContract',
        'outputs': [{'internalType': 'address', 'name': '', 'type': 'address'}],
        'stateMutability': 'view',
        'type': 'function',
    },
    {
        'inputs': [],
        'name': 'fastResultEnabled',
        'outputs': [{'internalType': 'bool', 'name': '', 'type': 'bool'}],
        'stateMutability': 'view',
        'type': 'function',
    },
    {
        'inputs': [{'internalType': 'address', 'name': 'owner', 'type': 'address'}],
        'name': 'getCurrentNonce',
        'outputs': [{'internalType': 'uint256', 'name': '', 'type': 'uint256'}],
        'stateMutability': 'view',
        'type': 'function',
    },
    {
        'inputs': [{'internalType': 'uint256[]', 'name': 'raceIDs', 'type': 'uint256[]'}],
        'name': 'getRacerCount',
        'outputs': [{'internalType': 'uint256[]', 'name': '', 'type': 'uint256[]'}],
        'stateMutability': 'view',
        'type': 'function',
    },
    {
        'inputs': [
            {'internalType': 'address', 'name': 'nftAddress', 'type': 'address'},
            {'internalType': 'address', 'name': 'tokenAddress', 'type': 'address'},
        ],
        'name': 'initialize',
        'outputs': [],
        'stateMutability': 'nonpayable',
        'type': 'function',
    },
    {
        'inputs': [],
        'name': 'isCompetitiveRacesEnabled',
        'outputs': [{'internalType': 'bool', 'name': '', 'type': 'bool'}],
        'stateMutability': 'view',
        'type': 'function',
    },
    {
        'inputs': [],
        'name': 'isDailyMissionsEnabled',
        'outputs': [{'internalType': 'bool', 'name': '', 'type': 'bool'}],
        'stateMutability': 'view',
        'type': 'function',
    },
    {
        'inputs': [],
        'name': 'isRewardClaimEnabled',
        'outputs': [{'internalType': 'bool', 'name': '', 'type': 'bool'}],
        'stateMutability': 'view',
        'type': 'function',
    },
    {
        'inputs': [
            {
                'components': [
                    {'internalType': 'uint256', 'name': 'raceID', 'type': 'uint256'},
                    {'internalType': 'uint256', 'name': 'tokenID', 'type': 'uint256'},
                    {'internalType': 'address', 'name': 'owner', 'type': 'address'},
                    {'internalType': 'uint256', 'name': 'fee', 'type': 'uint256'},
                    {'internalType': 'uint256', 'name': 'resultSize', 'type': 'uint256'},
                ],
                'internalType': 'struct SnailTrailRaceV2.CompetitiveRaceInfo',
                'name': 'raceInfo',
                'type': 'tuple',
            },
            {
                'components': [
                    {'internalType': 'uint256', 'name': 'raceID', 'type': 'uint256'},
                    {'internalType': 'int8', 'name': 'raceType', 'type': 'int8'},
                    {'internalType': 'address[]', 'name': 'winners', 'type': 'address[]'},
                    {'internalType': 'uint256[]', 'name': 'rewards', 'type': 'uint256[]'},
                ],
                'internalType': 'struct SnailTrailRaceV2.RaceResult',
                'name': 'raceResult',
                'type': 'tuple',
            },
            {'internalType': 'uint256', 'name': 'timeout', 'type': 'uint256'},
            {'internalType': 'uint256', 'name': 'salt', 'type': 'uint256'},
            {'internalType': 'bytes', 'name': 'sig', 'type': 'bytes'},
        ],
        'name': 'joinCompetitiveRace',
        'outputs': [],
        'stateMutability': 'nonpayable',
        'type': 'function',
    },
    {
        'inputs': [
            {
                'components': [
                    {'internalType': 'uint256', 'name': 'raceID', 'type': 'uint256'},
                    {'internalType': 'uint256', 'name': 'tokenID', 'type': 'uint256'},
                    {'internalType': 'address', 'name': 'owner', 'type': 'address'},
                ],
                'internalType': 'struct SnailTrailRaceV2.RaceInfo',
                'name': 'raceInfo',
                'type': 'tuple',
            },
            {'internalType': 'uint256', 'name': 'resultSize', 'type': 'uint256'},
            {
                'components': [
                    {
                        'components': [
                            {'internalType': 'uint256', 'name': 'raceID', 'type': 'uint256'},
                            {'internalType': 'int8', 'name': 'raceType', 'type': 'int8'},
                            {'internalType': 'address[]', 'name': 'winners', 'type': 'address[]'},
                            {'internalType': 'uint256[]', 'name': 'rewards', 'type': 'uint256[]'},
                        ],
                        'internalType': 'struct SnailTrailRaceV2.RaceResult',
                        'name': 'result1',
                        'type': 'tuple',
                    },
                    {
                        'components': [
                            {'internalType': 'uint256', 'name': 'raceID', 'type': 'uint256'},
                            {'internalType': 'int8', 'name': 'raceType', 'type': 'int8'},
                            {'internalType': 'address[]', 'name': 'winners', 'type': 'address[]'},
                            {'internalType': 'uint256[]', 'name': 'rewards', 'type': 'uint256[]'},
                        ],
                        'internalType': 'struct SnailTrailRaceV2.RaceResult',
                        'name': 'result2',
                        'type': 'tuple',
                    },
                ],
                'internalType': 'struct SnailTrailRaceV2.ResultWrapper',
                'name': 'results',
                'type': 'tuple',
            },
            {'internalType': 'uint256', 'name': 'timeout', 'type': 'uint256'},
            {'internalType': 'uint256', 'name': 'salt', 'type': 'uint256'},
            {'internalType': 'bytes', 'name': 'sig', 'type': 'bytes'},
        ],
        'name': 'joinDailyMission',
        'outputs': [],
        'stateMutability': 'nonpayable',
        'type': 'function',
    },
    {
        'inputs': [{'internalType': 'address', 'name': '', 'type': 'address'}],
        'name': 'nonceCounter',
        'outputs': [{'internalType': 'uint256', 'name': '', 'type': 'uint256'}],
        'stateMutability': 'view',
        'type': 'function',
    },
    {
        'inputs': [],
        'name': 'owner',
        'outputs': [{'internalType': 'address', 'name': '', 'type': 'address'}],
        'stateMutability': 'view',
        'type': 'function',
    },
    {
        'inputs': [{'internalType': 'uint256', 'name': '', 'type': 'uint256'}],
        'name': 'preCalculatedDailyRewards',
        'outputs': [{'internalType': 'uint256', 'name': '', 'type': 'uint256'}],
        'stateMutability': 'view',
        'type': 'function',
    },
    {
        'inputs': [{'internalType': 'uint256', 'name': '', 'type': 'uint256'}],
        'name': 'raceFeeTracker',
        'outputs': [{'internalType': 'uint256', 'name': '', 'type': 'uint256'}],
        'stateMutability': 'view',
        'type': 'function',
    },
    {
        'inputs': [
            {'internalType': 'uint256', 'name': '', 'type': 'uint256'},
            {'internalType': 'uint256', 'name': '', 'type': 'uint256'},
        ],
        'name': 'raceIDToAddress',
        'outputs': [{'internalType': 'address', 'name': '', 'type': 'address'}],
        'stateMutability': 'view',
        'type': 'function',
    },
    {
        'inputs': [{'internalType': 'uint256', 'name': '', 'type': 'uint256'}],
        'name': 'raceSubmissionTracker',
        'outputs': [{'internalType': 'bool', 'name': '', 'type': 'bool'}],
        'stateMutability': 'view',
        'type': 'function',
    },
    {
        'inputs': [{'internalType': 'uint256', 'name': '', 'type': 'uint256'}],
        'name': 'raceTypeTracker',
        'outputs': [{'internalType': 'enum SnailRaceType', 'name': '', 'type': 'uint8'}],
        'stateMutability': 'view',
        'type': 'function',
    },
    {'inputs': [], 'name': 'renounceOwnership', 'outputs': [], 'stateMutability': 'nonpayable', 'type': 'function'},
    {
        'inputs': [{'internalType': 'uint256', 'name': '', 'type': 'uint256'}],
        'name': 'rewardDistributionTracker',
        'outputs': [{'internalType': 'bool', 'name': '', 'type': 'bool'}],
        'stateMutability': 'view',
        'type': 'function',
    },
    {
        'inputs': [{'internalType': 'bool', 'name': 'isEnabled', 'type': 'bool'}],
        'name': 'setAutoClaimAfterResultEnabled',
        'outputs': [],
        'stateMutability': 'nonpayable',
        'type': 'function',
    },
    {
        'inputs': [{'internalType': 'address', 'name': 'newAddress', 'type': 'address'}],
        'name': 'setCompTreasuryContract',
        'outputs': [],
        'stateMutability': 'nonpayable',
        'type': 'function',
    },
    {
        'inputs': [{'internalType': 'bool', 'name': 'isEnabled', 'type': 'bool'}],
        'name': 'setCompetitiveRacesEnabled',
        'outputs': [],
        'stateMutability': 'nonpayable',
        'type': 'function',
    },
    {
        'inputs': [{'internalType': 'bool', 'name': 'isEnabled', 'type': 'bool'}],
        'name': 'setDailyMissionsEnabled',
        'outputs': [],
        'stateMutability': 'nonpayable',
        'type': 'function',
    },
    {
        'inputs': [{'internalType': 'address', 'name': 'newAddress', 'type': 'address'}],
        'name': 'setDailyTreasuryContract',
        'outputs': [],
        'stateMutability': 'nonpayable',
        'type': 'function',
    },
    {
        'inputs': [{'internalType': 'bool', 'name': 'isEnabled', 'type': 'bool'}],
        'name': 'setFastResultEnabled',
        'outputs': [],
        'stateMutability': 'nonpayable',
        'type': 'function',
    },
    {
        'inputs': [{'internalType': 'bool', 'name': 'isEnabled', 'type': 'bool'}],
        'name': 'setRewardClaimEnabled',
        'outputs': [],
        'stateMutability': 'nonpayable',
        'type': 'function',
    },
    {
        'inputs': [{'internalType': 'address', 'name': 'newAddress', 'type': 'address'}],
        'name': 'setSigner',
        'outputs': [],
        'stateMutability': 'nonpayable',
        'type': 'function',
    },
    {
        'inputs': [],
        'name': 'signerPublicAddress',
        'outputs': [{'internalType': 'address', 'name': '', 'type': 'address'}],
        'stateMutability': 'view',
        'type': 'function',
    },
    {
        'inputs': [{'internalType': 'address', 'name': 'newOwner', 'type': 'address'}],
        'name': 'transferOwnership',
        'outputs': [],
        'stateMutability': 'nonpayable',
        'type': 'function',
    },
    {'inputs': [], 'name': 'withdrawBalance', 'outputs': [], 'stateMutability': 'nonpayable', 'type': 'function'},
    {'inputs': [], 'name': 'withdrawErc20', 'outputs': [], 'stateMutability': 'nonpayable', 'type': 'function'},
    {'stateMutability': 'payable', 'type': 'receive'},
]
