# generated automatically from https://www.snailtrail.art/main.d3905bf907602c39.js - DO NOT MODIFY

CONTRACT = '0xec675B7C5471c67E9B203c6D1C604df28A89FB7f'

ABI = [
    {
        'inputs': [
            {'internalType': 'string', 'name': 'nftName', 'type': 'string'},
            {'internalType': 'string', 'name': 'nftSymbol', 'type': 'string'},
            {'internalType': 'string', 'name': 'baseTokenURI', 'type': 'string'},
        ],
        'stateMutability': 'nonpayable',
        'type': 'constructor',
    },
    {
        'anonymous': False,
        'inputs': [
            {'indexed': True, 'internalType': 'address', 'name': 'owner', 'type': 'address'},
            {'indexed': True, 'internalType': 'address', 'name': 'approved', 'type': 'address'},
            {'indexed': True, 'internalType': 'uint256', 'name': 'tokenId', 'type': 'uint256'},
        ],
        'name': 'Approval',
        'type': 'event',
    },
    {
        'anonymous': False,
        'inputs': [
            {'indexed': True, 'internalType': 'address', 'name': 'owner', 'type': 'address'},
            {'indexed': True, 'internalType': 'address', 'name': 'operator', 'type': 'address'},
            {'indexed': False, 'internalType': 'bool', 'name': 'approved', 'type': 'bool'},
        ],
        'name': 'ApprovalForAll',
        'type': 'event',
    },
    {
        'anonymous': False,
        'inputs': [
            {'indexed': True, 'internalType': 'uint256', 'name': '_id', 'type': 'uint256'},
            {'indexed': True, 'internalType': 'uint256', 'name': '_femaleID', 'type': 'uint256'},
            {'indexed': True, 'internalType': 'uint256', 'name': '_maleID', 'type': 'uint256'},
        ],
        'name': 'Breed',
        'type': 'event',
    },
    {
        'anonymous': False,
        'inputs': [{'indexed': True, 'internalType': 'uint256', 'name': '_id', 'type': 'uint256'}],
        'name': 'Burn',
        'type': 'event',
    },
    {
        'anonymous': False,
        'inputs': [{'indexed': True, 'internalType': 'uint256', 'name': '_id', 'type': 'uint256'}],
        'name': 'Claim',
        'type': 'event',
    },
    {
        'anonymous': False,
        'inputs': [{'indexed': True, 'internalType': 'uint256', 'name': '_id', 'type': 'uint256'}],
        'name': 'MarketingSnail',
        'type': 'event',
    },
    {
        'anonymous': False,
        'inputs': [{'indexed': True, 'internalType': 'uint256', 'name': '_id', 'type': 'uint256'}],
        'name': 'NewBorn',
        'type': 'event',
    },
    {
        'anonymous': False,
        'inputs': [
            {'indexed': True, 'internalType': 'address', 'name': 'previousOwner', 'type': 'address'},
            {'indexed': True, 'internalType': 'address', 'name': 'newOwner', 'type': 'address'},
        ],
        'name': 'OwnershipTransferred',
        'type': 'event',
    },
    {
        'anonymous': False,
        'inputs': [
            {'indexed': True, 'internalType': 'address', 'name': 'from', 'type': 'address'},
            {'indexed': True, 'internalType': 'address', 'name': 'to', 'type': 'address'},
            {'indexed': True, 'internalType': 'uint256', 'name': 'tokenId', 'type': 'uint256'},
        ],
        'name': 'Transfer',
        'type': 'event',
    },
    {'stateMutability': 'payable', 'type': 'fallback'},
    {
        'inputs': [],
        'name': 'INITIAL_SUPPLY',
        'outputs': [{'internalType': 'uint256', 'name': '', 'type': 'uint256'}],
        'stateMutability': 'view',
        'type': 'function',
    },
    {
        'inputs': [],
        'name': 'MARKETING_ALLOCATION',
        'outputs': [{'internalType': 'uint256', 'name': '', 'type': 'uint256'}],
        'stateMutability': 'view',
        'type': 'function',
    },
    {
        'inputs': [],
        'name': 'PUBLIC_ALLOCATION',
        'outputs': [{'internalType': 'uint256', 'name': '', 'type': 'uint256'}],
        'stateMutability': 'view',
        'type': 'function',
    },
    {
        'inputs': [],
        'name': 'SNAIL_PRICE',
        'outputs': [{'internalType': 'uint256', 'name': '', 'type': 'uint256'}],
        'stateMutability': 'view',
        'type': 'function',
    },
    {
        'inputs': [{'internalType': 'address', 'name': 'newContract', 'type': 'address'}],
        'name': 'addRecognizeContract',
        'outputs': [],
        'stateMutability': 'nonpayable',
        'type': 'function',
    },
    {
        'inputs': [],
        'name': 'antiBotMerkleRoot',
        'outputs': [{'internalType': 'bytes32', 'name': '', 'type': 'bytes32'}],
        'stateMutability': 'view',
        'type': 'function',
    },
    {
        'inputs': [{'internalType': 'bytes32[]', 'name': 'proof', 'type': 'bytes32[]'}],
        'name': 'antiBotMint',
        'outputs': [],
        'stateMutability': 'payable',
        'type': 'function',
    },
    {
        'inputs': [
            {'internalType': 'address', 'name': 'to', 'type': 'address'},
            {'internalType': 'uint256', 'name': 'tokenId', 'type': 'uint256'},
        ],
        'name': 'approve',
        'outputs': [],
        'stateMutability': 'nonpayable',
        'type': 'function',
    },
    {
        'inputs': [{'internalType': 'address', 'name': 'owner', 'type': 'address'}],
        'name': 'balanceOf',
        'outputs': [{'internalType': 'uint256', 'name': '', 'type': 'uint256'}],
        'stateMutability': 'view',
        'type': 'function',
    },
    {
        'inputs': [
            {'internalType': 'address', 'name': 'femaleSnailOwnerAddress', 'type': 'address'},
            {'internalType': 'uint256', 'name': 'femaleID', 'type': 'uint256'},
            {'internalType': 'uint256', 'name': 'maleID', 'type': 'uint256'},
        ],
        'name': 'breedSnail',
        'outputs': [],
        'stateMutability': 'nonpayable',
        'type': 'function',
    },
    {
        'inputs': [{'internalType': 'uint256', 'name': 'tokenID', 'type': 'uint256'}],
        'name': 'burnSnail',
        'outputs': [],
        'stateMutability': 'nonpayable',
        'type': 'function',
    },
    {
        'inputs': [{'internalType': 'address', 'name': 'userAddress', 'type': 'address'}],
        'name': 'generateSnail',
        'outputs': [],
        'stateMutability': 'nonpayable',
        'type': 'function',
    },
    {
        'inputs': [{'internalType': 'uint256', 'name': 'tokenId', 'type': 'uint256'}],
        'name': 'getApproved',
        'outputs': [{'internalType': 'address', 'name': '', 'type': 'address'}],
        'stateMutability': 'view',
        'type': 'function',
    },
    {
        'inputs': [],
        'name': 'getRemainingWhitelistSpot',
        'outputs': [{'internalType': 'uint256', 'name': '', 'type': 'uint256'}],
        'stateMutability': 'view',
        'type': 'function',
    },
    {
        'inputs': [],
        'name': 'grossAmount',
        'outputs': [{'internalType': 'uint256', 'name': '', 'type': 'uint256'}],
        'stateMutability': 'view',
        'type': 'function',
    },
    {
        'inputs': [
            {'internalType': 'address', 'name': 'owner', 'type': 'address'},
            {'internalType': 'address', 'name': 'operator', 'type': 'address'},
        ],
        'name': 'isApprovedForAll',
        'outputs': [{'internalType': 'bool', 'name': '', 'type': 'bool'}],
        'stateMutability': 'view',
        'type': 'function',
    },
    {
        'inputs': [{'internalType': 'address', 'name': 'newContract', 'type': 'address'}],
        'name': 'isContractRecognized',
        'outputs': [{'internalType': 'bool', 'name': 'isRecognized', 'type': 'bool'}],
        'stateMutability': 'view',
        'type': 'function',
    },
    {
        'inputs': [],
        'name': 'isPostWhitelistMintEnabled',
        'outputs': [{'internalType': 'bool', 'name': '', 'type': 'bool'}],
        'stateMutability': 'view',
        'type': 'function',
    },
    {
        'inputs': [],
        'name': 'isPublicMintEnabled',
        'outputs': [{'internalType': 'bool', 'name': '', 'type': 'bool'}],
        'stateMutability': 'view',
        'type': 'function',
    },
    {
        'inputs': [],
        'name': 'isWhitelistMintEnabled',
        'outputs': [{'internalType': 'bool', 'name': '', 'type': 'bool'}],
        'stateMutability': 'view',
        'type': 'function',
    },
    {
        'inputs': [{'internalType': 'uint256', 'name': 'n', 'type': 'uint256'}],
        'name': 'mint',
        'outputs': [],
        'stateMutability': 'payable',
        'type': 'function',
    },
    {
        'inputs': [{'internalType': 'address', 'name': 'giftToAddress', 'type': 'address'}],
        'name': 'mintMarketingSnail',
        'outputs': [],
        'stateMutability': 'nonpayable',
        'type': 'function',
    },
    {
        'inputs': [],
        'name': 'minted',
        'outputs': [{'internalType': 'uint256', 'name': '', 'type': 'uint256'}],
        'stateMutability': 'view',
        'type': 'function',
    },
    {
        'inputs': [],
        'name': 'name',
        'outputs': [{'internalType': 'string', 'name': '', 'type': 'string'}],
        'stateMutability': 'view',
        'type': 'function',
    },
    {
        'inputs': [],
        'name': 'newBornCount',
        'outputs': [{'internalType': 'uint256', 'name': '', 'type': 'uint256'}],
        'stateMutability': 'view',
        'type': 'function',
    },
    {
        'inputs': [],
        'name': 'owner',
        'outputs': [{'internalType': 'address', 'name': '', 'type': 'address'}],
        'stateMutability': 'view',
        'type': 'function',
    },
    {
        'inputs': [{'internalType': 'uint256', 'name': 'tokenId', 'type': 'uint256'}],
        'name': 'ownerOf',
        'outputs': [{'internalType': 'address', 'name': '', 'type': 'address'}],
        'stateMutability': 'view',
        'type': 'function',
    },
    {'inputs': [], 'name': 'renounceOwnership', 'outputs': [], 'stateMutability': 'nonpayable', 'type': 'function'},
    {
        'inputs': [
            {'internalType': 'address', 'name': 'from', 'type': 'address'},
            {'internalType': 'address', 'name': 'to', 'type': 'address'},
            {'internalType': 'uint256', 'name': 'tokenId', 'type': 'uint256'},
        ],
        'name': 'safeTransferFrom',
        'outputs': [],
        'stateMutability': 'nonpayable',
        'type': 'function',
    },
    {
        'inputs': [
            {'internalType': 'address', 'name': 'from', 'type': 'address'},
            {'internalType': 'address', 'name': 'to', 'type': 'address'},
            {'internalType': 'uint256', 'name': 'tokenId', 'type': 'uint256'},
            {'internalType': 'bytes', 'name': '_data', 'type': 'bytes'},
        ],
        'name': 'safeTransferFrom',
        'outputs': [],
        'stateMutability': 'nonpayable',
        'type': 'function',
    },
    {
        'inputs': [{'internalType': 'bytes32', 'name': 'newRoot', 'type': 'bytes32'}],
        'name': 'setAntiBotRoot',
        'outputs': [],
        'stateMutability': 'nonpayable',
        'type': 'function',
    },
    {
        'inputs': [
            {'internalType': 'address', 'name': 'operator', 'type': 'address'},
            {'internalType': 'bool', 'name': 'approved', 'type': 'bool'},
        ],
        'name': 'setApprovalForAll',
        'outputs': [],
        'stateMutability': 'nonpayable',
        'type': 'function',
    },
    {
        'inputs': [{'internalType': 'string', 'name': 'uri', 'type': 'string'}],
        'name': 'setBaseUri',
        'outputs': [],
        'stateMutability': 'nonpayable',
        'type': 'function',
    },
    {
        'inputs': [{'internalType': 'bool', 'name': 'isEnabled', 'type': 'bool'}],
        'name': 'setPostWhitelistMintEnabled',
        'outputs': [],
        'stateMutability': 'nonpayable',
        'type': 'function',
    },
    {
        'inputs': [{'internalType': 'bool', 'name': 'isEnabled', 'type': 'bool'}],
        'name': 'setPublicMintEnabled',
        'outputs': [],
        'stateMutability': 'nonpayable',
        'type': 'function',
    },
    {
        'inputs': [
            {'internalType': 'address[]', 'name': 'snailAddresses', 'type': 'address[]'},
            {'internalType': 'uint8', 'name': 'allocation', 'type': 'uint8'},
        ],
        'name': 'setSnailsAllocation',
        'outputs': [],
        'stateMutability': 'nonpayable',
        'type': 'function',
    },
    {
        'inputs': [{'internalType': 'bool', 'name': 'isEnabled', 'type': 'bool'}],
        'name': 'setWhitelistMintEnabled',
        'outputs': [],
        'stateMutability': 'nonpayable',
        'type': 'function',
    },
    {
        'inputs': [{'internalType': 'bytes4', 'name': 'interfaceId', 'type': 'bytes4'}],
        'name': 'supportsInterface',
        'outputs': [{'internalType': 'bool', 'name': '', 'type': 'bool'}],
        'stateMutability': 'view',
        'type': 'function',
    },
    {
        'inputs': [],
        'name': 'symbol',
        'outputs': [{'internalType': 'string', 'name': '', 'type': 'string'}],
        'stateMutability': 'view',
        'type': 'function',
    },
    {
        'inputs': [{'internalType': 'uint256', 'name': 'index', 'type': 'uint256'}],
        'name': 'tokenByIndex',
        'outputs': [{'internalType': 'uint256', 'name': '', 'type': 'uint256'}],
        'stateMutability': 'view',
        'type': 'function',
    },
    {
        'inputs': [
            {'internalType': 'address', 'name': 'owner', 'type': 'address'},
            {'internalType': 'uint256', 'name': 'index', 'type': 'uint256'},
        ],
        'name': 'tokenOfOwnerByIndex',
        'outputs': [{'internalType': 'uint256', 'name': '', 'type': 'uint256'}],
        'stateMutability': 'view',
        'type': 'function',
    },
    {
        'inputs': [{'internalType': 'uint256', 'name': 'tokenId', 'type': 'uint256'}],
        'name': 'tokenURI',
        'outputs': [{'internalType': 'string', 'name': '', 'type': 'string'}],
        'stateMutability': 'view',
        'type': 'function',
    },
    {
        'inputs': [],
        'name': 'totalSupply',
        'outputs': [{'internalType': 'uint256', 'name': '', 'type': 'uint256'}],
        'stateMutability': 'view',
        'type': 'function',
    },
    {
        'inputs': [
            {'internalType': 'address', 'name': 'from', 'type': 'address'},
            {'internalType': 'address', 'name': 'to', 'type': 'address'},
            {'internalType': 'uint256', 'name': 'tokenId', 'type': 'uint256'},
        ],
        'name': 'transferFrom',
        'outputs': [],
        'stateMutability': 'nonpayable',
        'type': 'function',
    },
    {
        'inputs': [{'internalType': 'address', 'name': 'newOwner', 'type': 'address'}],
        'name': 'transferOwnership',
        'outputs': [],
        'stateMutability': 'nonpayable',
        'type': 'function',
    },
    {'inputs': [], 'name': 'withdrawBalance', 'outputs': [], 'stateMutability': 'nonpayable', 'type': 'function'},
    {'stateMutability': 'payable', 'type': 'receive'},
]
